# Generated by Django 2.0.3 on 2019-10-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
