# Generated by Django 2.0.3 on 2019-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_transaction_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
