# Generated by Django 2.0.3 on 2019-10-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_transaction_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
