# Generated by Django 2.0.3 on 2019-11-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20191001_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
