# Generated by Django 2.0.3 on 2018-08-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180813_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('priority',)},
        ),
    ]
