# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-05 18:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('text', ckeditor.fields.RichTextField(verbose_name='Text')),
                ('date_create', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('phone1', models.TextField(max_length=20)),
                ('phone2', models.TextField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Link')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Category'),
        ),
    ]
