# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-05 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='Title',
            new_name='title',
        ),
    ]
