# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-01 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='', upload_to='/home/askar/PROJECTS/kochkorAd/webapp_root/media/ad'),
        ),
    ]
