# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-01 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170901_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
