# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170901_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ad')),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.AddField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webapp.Ad'),
        ),
    ]
