# Generated by Django 2.0.3 on 2018-06-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_phone_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='phone2',
        ),
    ]
