# Generated by Django 2.0.3 on 2018-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180603_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-view_count']},
        ),
        migrations.AddField(
            model_name='category',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
