# Generated by Django 2.0.3 on 2018-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '00012_change_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
